export interface TaskRow {
  client_name: string;
  project_name: string;
  activity_name: string;
  task_title: string;
  hours_spent: number | string;
  description?: string;
}

export function employeeDailyReportEmail(opts: {
  name: string;
  date: string;
  total_hours: number;
  tasks: TaskRow[];
}) {
  const { name, date, total_hours, tasks } = opts;
  const rows = tasks.length
    ? tasks
        .map(
          (t) => `
        <tr>
          <td style="padding:6px 10px;border:1px solid #e5e7eb;">${escape(t.client_name)}</td>
          <td style="padding:6px 10px;border:1px solid #e5e7eb;">${escape(t.project_name)}</td>
          <td style="padding:6px 10px;border:1px solid #e5e7eb;">${escape(t.activity_name)}</td>
          <td style="padding:6px 10px;border:1px solid #e5e7eb;">${escape(t.task_title)}</td>
          <td style="padding:6px 10px;border:1px solid #e5e7eb;text-align:right;">${t.hours_spent}</td>
        </tr>`,
        )
        .join('')
    : `<tr><td colspan="5" style="padding:12px;text-align:center;color:#6b7280;border:1px solid #e5e7eb;">
         No tasks submitted yet for today.
       </td></tr>`;

  return `
  <div style="font-family:Arial,sans-serif;max-width:680px;margin:0 auto;color:#111827;">
    <h2 style="margin-bottom:4px;">Hi ${escape(name)},</h2>
    <p style="color:#374151;margin-top:0;">Here is your daily task report for <strong>${date}</strong>.</p>
    <div style="background:#f3f4f6;border-radius:8px;padding:12px 16px;margin:16px 0;">
      <strong>Total hours logged today:</strong> ${total_hours.toFixed(2)} h<br/>
      <strong>Tasks submitted:</strong> ${tasks.length}
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      <thead>
        <tr style="background:#111827;color:#fff;">
          <th style="padding:8px 10px;text-align:left;">Client</th>
          <th style="padding:8px 10px;text-align:left;">Project</th>
          <th style="padding:8px 10px;text-align:left;">Activity</th>
          <th style="padding:8px 10px;text-align:left;">Task</th>
          <th style="padding:8px 10px;text-align:right;">Hours</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
    <p style="color:#6b7280;font-size:12px;margin-top:24px;">
      This is an automated report generated by the Employee App.
    </p>
  </div>`;
}

export function adminDailySummaryEmail(opts: {
  date: string;
  rows: { employee_name: string; task_count: number; total_hours: number }[];
  grand_total_hours: number;
  grand_total_tasks: number;
}) {
  const { date, rows, grand_total_hours, grand_total_tasks } = opts;
  const body = rows.length
    ? rows
        .map(
          (r) => `
        <tr>
          <td style="padding:6px 10px;border:1px solid #e5e7eb;">${escape(r.employee_name)}</td>
          <td style="padding:6px 10px;border:1px solid #e5e7eb;text-align:right;">${r.task_count}</td>
          <td style="padding:6px 10px;border:1px solid #e5e7eb;text-align:right;">${r.total_hours.toFixed(2)}</td>
        </tr>`,
        )
        .join('')
    : `<tr><td colspan="3" style="padding:12px;text-align:center;color:#6b7280;border:1px solid #e5e7eb;">
         No active employees found.
       </td></tr>`;

  return `
  <div style="font-family:Arial,sans-serif;max-width:680px;margin:0 auto;color:#111827;">
    <h2 style="margin-bottom:4px;">Team Daily Summary</h2>
    <p style="color:#374151;margin-top:0;">Employee task activity for <strong>${date}</strong>.</p>
    <div style="background:#f3f4f6;border-radius:8px;padding:12px 16px;margin:16px 0;">
      <strong>Total hours logged:</strong> ${grand_total_hours.toFixed(2)} h<br/>
      <strong>Total tasks:</strong> ${grand_total_tasks}<br/>
      <strong>Employees:</strong> ${rows.length}
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      <thead>
        <tr style="background:#111827;color:#fff;">
          <th style="padding:8px 10px;text-align:left;">Employee</th>
          <th style="padding:8px 10px;text-align:right;">Tasks</th>
          <th style="padding:8px 10px;text-align:right;">Hours</th>
        </tr>
      </thead>
      <tbody>${body}</tbody>
    </table>
    <p style="color:#6b7280;font-size:12px;margin-top:24px;">
      This is an automated summary generated by the Employee App.
    </p>
  </div>`;
}

export function reminderEmail(name: string, date: string) {
  return `
  <div style="font-family:Arial,sans-serif;max-width:680px;margin:0 auto;color:#111827;">
    <h2>Hi ${escape(name)},</h2>
    <p>You haven't submitted your daily task report for <strong>${date}</strong> yet.</p>
    <p>Please log in to the Employee App and submit your tasks.</p>
  </div>`;
}

function escape(s: string = '') {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
